# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_answerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.AnswerKey')),
            ],
        ),
    ]
