# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField()),
                ('version', models.IntegerField()),
                ('discipline', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='todo.AnswerKey'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='official_answer_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.OfficialAnswerKey'),
        ),
    ]
